# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LGaxKME9_3oluNiNer6sprCV7c9w1HDU
"""

import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "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")

from openai import OpenAI

client = OpenAI(api_key=OPENAI_API_KEY)

def generate_text(prompt):
    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are a real estate marketing expert."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7
        )

        return response.choices[0].message.content.strip()

    except Exception as e:
        print("OpenAI Error:", str(e))
        return "Error generating content"

data = {
    "location": "Melbourne",
    "size": "1200 sq ft",
    "price": "AUD 550,000",
    "bedrooms": "3 BHK",
    "bathrooms": "2",
    "kitchen": "Modular kitchen",
    "Parking": "2 Vehicles",
    "additional_features": "Balcony"
}

prompt = f"""
Create real estate content in a formal tone.

Property Details:
Location: {data['location']}
Size: {data['size']}
Price: {data['price']}
Bedrooms: {data['bedrooms']}
Bathrooms/Toilets: {data['bathrooms']}
Kitchen: {data['kitchen']}

Additional Features:
{data['additional_features']}

Generate:
1. Property Listing Description
2. Social Media Post
3. Professional Email
4. Video Script
"""

response = generate_text(prompt)

from IPython.display import display, Markdown

display(Markdown(response))

